### ISSUE TITLE
Script not working...

### ISSUE THREAD

**Issue by erikdemarco** [gabizz/hestiacp-scriptline-generator#2]
The ‘content’ attribute of Window objects is deprecated.  Please use ‘window.top’ instead. hestiacp-scriptline-generator:143:6

TypeError: content.insertAdjacentHTML is not a function
hestiacp-scriptline-generator:143:15

ReferenceError: createScript is not definedhestiacp-scriptline-generator:105:6

**Comment by gabizz** [comment]
now it does. it was almost completely rewritten. it should work in any modern browser, being based on react.js and material-ui. sorry for taking so long...
