### ISSUE TITLE
Add additional details for Cloudflare

### ISSUE THREAD

**Issue by bensonsts** [gabizz/hestiacp-scriptline-generator#8]
To use Cloudflare origin SSL for maximum performance, you also get 15 year certificates and don’t need to worry about updating certificates for while 🙂

To do this, you can add the Cloudflare certificate authority to your server like this:

```
sudo su -

wget https://developers.cloudflare.com/ssl/static/origin_ca_rsa_root.pem

mv origin_ca_rsa_root.pem origin_ca_rsa_root.crt

cp origin_ca_rsa_root.crt /usr/local/share/ca-certificates

update-ca-certificates
```
[Source from](https://ideaspot.com.au/blog/cloudflare-hestia-setup/)

**Comment by jaapmarcus** [comment]
This is not related to the script line generator it self
